"""add_name_to_wallet

Revision ID: 12ce6dda9bc2
Revises: fcce885d1aa0
Create Date: 2026-06-21 14:19:56.497860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ce6dda9bc2'
down_revision: Union[str, None] = 'fcce885d1aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'name')
    # ### end Alembic commands ###
