"""add player position and default_team to users

Revision ID: 14f3e224b1d4
Revises: 791ef9b146cf
Create Date: 2026-07-25 07:35:09.103034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f3e224b1d4'
down_revision: Union[str, None] = '791ef9b146cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('default_team', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_team')
    op.drop_column('users', 'position')
    # ### end Alembic commands ###
