"""link training and tournament to group

Revision ID: 1aa2bed3f386
Revises: 3f1c58ad72e4
Create Date: 2026-09-25 12:13:33.725052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa2bed3f386'
down_revision: Union[str, None] = '3f1c58ad72e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerated, with the two foreign keys named by hand: autogenerate
    # emits create_foreign_key(None, ...) and a matching drop_constraint(None,
    # ...), and the unnamed drop fails on Postgres.
    op.add_column('tournament', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tournament_group_id'), 'tournament', ['group_id'], unique=False)
    op.create_foreign_key(
        'fk_tournament_group_id', 'tournament', 'group', ['group_id'], ['id'],
        ondelete='SET NULL',
    )
    op.add_column('training', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_training_group_id'), 'training', ['group_id'], unique=False)
    op.create_foreign_key(
        'fk_training_group_id', 'training', 'group', ['group_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_training_group_id', 'training', type_='foreignkey')
    op.drop_index(op.f('ix_training_group_id'), table_name='training')
    op.drop_column('training', 'group_id')
    op.drop_constraint('fk_tournament_group_id', 'tournament', type_='foreignkey')
    op.drop_index(op.f('ix_tournament_group_id'), table_name='tournament')
    op.drop_column('tournament', 'group_id')
    # ### end Alembic commands ###
