"""drop training_type and swimming_discipline tables

Revision ID: 2140c095f678
Revises: 986eddaf2249
Create Date: 2026-07-12 12:02:57.622744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2140c095f678'
down_revision: Union[str, None] = '986eddaf2249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_type_id', table_name='training_type')
    op.drop_table('training_type')
    op.drop_index('ix_swimming_discipline_id', table_name='swimming_discipline')
    op.drop_table('swimming_discipline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swimming_discipline',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='swimming_discipline_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='swimming_discipline_pkey')
    )
    op.create_index('ix_swimming_discipline_id', 'swimming_discipline', ['id'], unique=False)
    op.create_table('training_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='training_type_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='training_type_pkey')
    )
    op.create_index('ix_training_type_id', 'training_type', ['id'], unique=False)
    # ### end Alembic commands ###
