"""billing model b: membership selection+billing_type, contract snapshot, group rename

Revision ID: 27aa73f410d3
Revises: 71ae0c464615
Create Date: 2026-09-24 15:49:45.952671

MEMBERSHIP billing moves from a finite installments_list agreed at signing to
open-ended recurring billing, with a separate TERM type for one fixed block.

  * membership gains selection_id (a plan prices one squad), billing_type,
    price and term_months, and loses months_count / price_month /
    installments_count. Its catalog key becomes
    (company_id, selection_id, program, billing_type), so `name` is now just a
    label and is nullable.
  * contract gains billing_type and term_months, snapshotted from the plan at
    signing. Its `amount` is REDEFINED (no DDL change) as the per-installment
    price rather than a term total.
  * season_selection_user splits into `group` (season + selection — the
    squad itself, and the unit debt is reported over) and `group_user`
    (who is in it).

Autogenerated, then adjusted:
  * The NUMERIC -> UUID alter_column noise on company / expense_category /
    income_category / payment / users / wallet was REMOVED. SQLite renders the
    UUID columns as NUMERIC, so autogenerate reports a change on every run;
    it predates this migration and is not ours to make.
  * The `billingtype` enum is created once up front for Postgres rather than
    by each add_column, and renders as a plain VARCHAR on SQLite — the same
    helper shape 874bdb0952e7 uses for `program`.
  * season_selection_user was reported as drop_table + create_table, which
    would throw the roster away. Replaced with create / INSERT..SELECT / drop
    that splits each old row into a `group` (deduplicated per season+selection)
    and a `group_user`. `group` is a reserved SQL word, hence the quoting in
    the raw SQL below.
  * membership's new NOT NULL columns are added nullable, BACKFILLED from the
    old ones, then tightened:
        billing_type <- MONTHLY when months_count = 1, else TERM
        price        <- price_month for MONTHLY, price_month * months_count
                        for TERM (the old term total)
        term_months  <- NULL for MONTHLY, months_count for TERM
    selection_id is new information with no derivable value, so existing rows
    are PARKED on their company's lowest-id active selection and the run
    prints how many to re-point. Failing instead would be a dead end: the
    column does not exist until this migration runs, so an operator told to
    map the rows first would have nowhere to write the mapping. A company with
    no active selection at all still stops the run.
  * membership's constraint/column drops run inside batch_alter_table so
    SQLite (which cannot ALTER or DROP CONSTRAINT) rebuilds the table.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

# revision identifiers, used by Alembic.
revision: str = '27aa73f410d3'
down_revision: Union[str, None] = '71ae0c464615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _billing_type(dialect: str):
    """The enum type, created once up front — never auto-CREATE it per column."""
    if dialect == "postgresql":
        return PG_ENUM("MONTHLY", "TERM", name="billingtype", create_type=False)
    return sa.String(20)


def upgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name
    billing_type = _billing_type(dialect)

    if dialect == "postgresql":
        bind.execute(text("""
            DO $$ BEGIN
                CREATE TYPE billingtype AS ENUM ('MONTHLY', 'TERM');
            EXCEPTION
                WHEN duplicate_object THEN NULL;
            END $$;
        """))

    # ── season_selection_user -> group + group_user ─────────────────
    # The old table mixed two things: which squad exists (season, selection)
    # and who is in it. They split here, so the rows are redistributed rather
    # than renamed. "group" is reserved, hence the quoting in the raw SQL.
    op.create_table(
        'group',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('season_id', sa.Integer(), nullable=False),
        sa.Column('selection_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['selection_id'], ['selection.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('season_id', 'selection_id', name='uq_group_season_selection'),
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_index(op.f('ix_group_season_id'), 'group', ['season_id'], unique=False)
    op.create_index(op.f('ix_group_selection_id'), 'group', ['selection_id'], unique=False)

    op.create_table(
        'group_user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('group_id', 'user_id', name='uq_group_user'),
    )
    op.create_index(op.f('ix_group_user_id'), 'group_user', ['id'], unique=False)
    op.create_index(op.f('ix_group_user_group_id'), 'group_user', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_user_user_id'), 'group_user', ['user_id'], unique=False)

    # One group per distinct (season, selection) that the old table mentions...
    bind.execute(text(
        'INSERT INTO "group" (season_id, selection_id) '
        'SELECT DISTINCT season_id, selection_id FROM season_selection_user'
    ))
    # ...then every old row becomes a membership of the matching group.
    bind.execute(text(
        'INSERT INTO group_user (group_id, user_id, created_at) '
        'SELECT g.id, ssu.user_id, ssu.created_at '
        'FROM season_selection_user ssu '
        'JOIN "group" g ON g.season_id = ssu.season_id '
        '                AND g.selection_id = ssu.selection_id'
    ))

    op.drop_index('ix_season_selection_user_id', table_name='season_selection_user')
    op.drop_index('ix_season_selection_user_season_id', table_name='season_selection_user')
    op.drop_index('ix_season_selection_user_selection_id', table_name='season_selection_user')
    op.drop_index('ix_season_selection_user_user_id', table_name='season_selection_user')
    op.drop_table('season_selection_user')

    # ── contract: the plan snapshot ─────────────────────────────────
    op.add_column('contract', sa.Column('billing_type', billing_type, nullable=True))
    op.add_column('contract', sa.Column('term_months', sa.Integer(), nullable=True))

    # ── membership: add nullable, backfill, then tighten ────────────
    op.add_column('membership', sa.Column('selection_id', sa.Integer(), nullable=True))
    op.add_column('membership', sa.Column('billing_type', billing_type, nullable=True))
    op.add_column('membership', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('membership', sa.Column('term_months', sa.Integer(), nullable=True))

    # Postgres will not assign a bare text literal to an enum column, and
    # SQLite has no such type to cast to — hence the dialect-dependent suffix.
    cast = "::billingtype" if dialect == "postgresql" else ""
    bind.execute(text(f"""
        UPDATE membership SET
            billing_type = (CASE WHEN months_count = 1
                                 THEN 'MONTHLY' ELSE 'TERM' END){cast},
            price        = CASE WHEN months_count = 1
                                THEN price_month
                                ELSE price_month * months_count END,
            term_months  = CASE WHEN months_count = 1 THEN NULL ELSE months_count END
    """))

    # selection_id is genuinely NEW information — an old plan priced a whole
    # company, not a squad. There is no way to recover which selection was
    # meant, so each row is parked on its company's lowest-id active selection
    # and the operator re-points it afterwards. Guessing here beats failing
    # mid-migration: the column does not exist until this runs, so an operator
    # told to "map them first" would have nowhere to write the mapping.
    to_park = bind.execute(text(
        "SELECT COUNT(*) FROM membership WHERE selection_id IS NULL"
    )).scalar()

    # Bare `s.is_active` rather than `= 1`/`= true`: Postgres needs a boolean
    # expression and SQLite reads its stored 1 as true, so this suits both.
    bind.execute(text("""
        UPDATE membership SET selection_id = (
            SELECT MIN(s.id) FROM selection s
            WHERE s.company_id = membership.company_id AND s.is_active
        )
        WHERE selection_id IS NULL
    """))

    stranded = bind.execute(text(
        "SELECT COUNT(*) FROM membership WHERE selection_id IS NULL"
    )).scalar()
    if stranded:
        raise RuntimeError(
            f"{stranded} membership row(s) belong to a company with no active "
            f"selection, so they cannot be parked anywhere. Create a selection "
            f"for those companies (or delete the obsolete plans) and re-run."
        )

    if to_park:
        print(
            f"  [billing model b] {to_park} membership row(s) were parked on "
            f"their company's first active selection. Re-point any that belong "
            f"to a different squad:\n"
            f"      UPDATE membership SET selection_id = <selection> WHERE id = <id>;"
        )

    with op.batch_alter_table('membership') as batch:
        batch.alter_column('selection_id', existing_type=sa.Integer(), nullable=False)
        batch.alter_column('billing_type', existing_type=billing_type, nullable=False)
        batch.alter_column('price', existing_type=sa.Numeric(precision=10, scale=2),
                           nullable=False)
        batch.alter_column('name', existing_type=sa.VARCHAR(length=255), nullable=True)
        batch.drop_constraint('uq_membership_company_name_program', type_='unique')
        batch.create_unique_constraint(
            'uq_membership_company_selection_program_type',
            ['company_id', 'selection_id', 'program', 'billing_type'],
        )
        batch.create_foreign_key(
            'fk_membership_selection_id', 'selection', ['selection_id'], ['id']
        )
        batch.drop_column('price_month')
        batch.drop_column('months_count')
        batch.drop_column('installments_count')

    op.create_index(op.f('ix_membership_selection_id'), 'membership',
                    ['selection_id'], unique=False)


def downgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name
    billing_type = _billing_type(dialect)

    # ── membership: restore the old shape ───────────────────────────
    # server_default so the NOT NULL columns can be re-added to a table that
    # already has rows (autogenerate omits it); dropped again afterwards so
    # the model stays the only place a default lives.
    op.drop_index(op.f('ix_membership_selection_id'), table_name='membership')
    op.add_column('membership', sa.Column(
        'installments_count', sa.INTEGER(), nullable=False, server_default='1'))
    op.add_column('membership', sa.Column(
        'months_count', sa.INTEGER(), nullable=False, server_default='1'))
    op.add_column('membership', sa.Column(
        'price_month', sa.NUMERIC(precision=10, scale=2), nullable=False,
        server_default='0'))

    bind.execute(text("""
        UPDATE membership SET
            months_count = CASE WHEN billing_type = 'TERM'
                                THEN COALESCE(term_months, 1) ELSE 1 END,
            price_month  = CASE WHEN billing_type = 'TERM' AND COALESCE(term_months, 0) > 0
                                THEN price / term_months
                                ELSE price END
    """))

    with op.batch_alter_table('membership') as batch:
        batch.alter_column('installments_count', existing_type=sa.INTEGER(),
                           server_default=None)
        batch.alter_column('months_count', existing_type=sa.INTEGER(),
                           server_default=None)
        batch.alter_column('price_month', existing_type=sa.NUMERIC(precision=10, scale=2),
                           server_default=None)
        batch.drop_constraint('fk_membership_selection_id', type_='foreignkey')
        batch.drop_constraint('uq_membership_company_selection_program_type',
                              type_='unique')
        batch.create_unique_constraint(
            'uq_membership_company_name_program', ['company_id', 'name', 'program'])
        batch.alter_column('name', existing_type=sa.VARCHAR(length=255), nullable=False)
        batch.drop_column('term_months')
        batch.drop_column('price')
        batch.drop_column('billing_type')
        batch.drop_column('selection_id')

    # ── contract ────────────────────────────────────────────────────
    op.drop_column('contract', 'term_months')
    op.drop_column('contract', 'billing_type')

    # ── group + group_user -> season_selection_user ─────────────────
    op.create_table(
        'season_selection_user',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('season_id', sa.INTEGER(), nullable=False),
        sa.Column('selection_id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('created_at', sa.DATETIME(),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['selection_id'], ['selection.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('season_id', 'selection_id', 'user_id',
                            name='uq_season_selection_user'),
    )
    op.create_index('ix_season_selection_user_id', 'season_selection_user',
                    ['id'], unique=False)
    op.create_index('ix_season_selection_user_season_id', 'season_selection_user',
                    ['season_id'], unique=False)
    op.create_index('ix_season_selection_user_selection_id', 'season_selection_user',
                    ['selection_id'], unique=False)
    op.create_index('ix_season_selection_user_user_id', 'season_selection_user',
                    ['user_id'], unique=False)

    # Flatten the pair back into one row per member. A group with no members
    # has nothing to flatten and is simply lost — the old shape cannot express
    # an empty squad.
    bind.execute(text(
        'INSERT INTO season_selection_user '
        '(season_id, selection_id, user_id, created_at) '
        'SELECT g.season_id, g.selection_id, gu.user_id, gu.created_at '
        'FROM group_user gu JOIN "group" g ON g.id = gu.group_id'
    ))

    op.drop_index(op.f('ix_group_user_user_id'), table_name='group_user')
    op.drop_index(op.f('ix_group_user_group_id'), table_name='group_user')
    op.drop_index(op.f('ix_group_user_id'), table_name='group_user')
    op.drop_table('group_user')
    op.drop_index(op.f('ix_group_selection_id'), table_name='group')
    op.drop_index(op.f('ix_group_season_id'), table_name='group')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')

    if dialect == "postgresql":
        billing_type.drop(bind, checkfirst=True)
