"""make segment_sparring opponent_company_id nullable

Revision ID: 36d221b51459
Revises: f9fec0309acd
Create Date: 2026-07-19 08:25:25.575987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d221b51459'
down_revision: Union[str, None] = 'f9fec0309acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segment_sparring', 'opponent_company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segment_sparring', 'opponent_company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
