"""add payment status DEBT

Revision ID: 3f1c58ad72e4
Revises: 27aa73f410d3
Create Date: 2026-09-25 10:12:00.000000

A due starts PENDING and becomes DEBT once its due date has passed and it is
still unpaid (see _daily_debt_job). DEBT is still outstanding money — it only
marks the due as late — so every "outstanding" query accepts both
(payment_model.OUTSTANDING_STATUSES).

Hand-written, not autogenerated: alembic does not diff enum VALUES, so a new
label on an existing type is invisible to --autogenerate.

Postgres notes:
  * `payment.status` is a native `paymentstatus` enum, so the label has to be
    added with ALTER TYPE. IF NOT EXISTS makes a re-run harmless.
  * ALTER TYPE ... ADD VALUE cannot run inside a transaction block that later
    uses the new label, so this migration commits the DDL on its own
    connection before returning. Nothing else here touches the type.
  * Downgrade rebuilds the type without DEBT, because Postgres has no
    DROP VALUE. Any row still sitting on DEBT is moved back to PENDING first —
    the state it came from, and still correct: the money is owed either way.

SQLite renders the enum as VARCHAR with no separate type, so it needs no DDL
at all — the label is a Python-side concern there.
"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '3f1c58ad72e4'
down_revision: Union[str, None] = '27aa73f410d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    # Outside the migration's transaction: ADD VALUE is not usable in the same
    # transaction that would reference the new label.
    with bind.engine.connect() as conn:
        conn = conn.execution_options(isolation_level="AUTOCOMMIT")
        conn.execute(text("ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'DEBT'"))


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    # No DROP VALUE in Postgres: rebuild the type without DEBT. Rows on DEBT go
    # back to PENDING — where they came from, and still outstanding.
    bind.execute(text(
        "UPDATE payment SET status = 'PENDING' WHERE status = 'DEBT'"
    ))
    bind.execute(text("ALTER TYPE paymentstatus RENAME TO paymentstatus_old"))
    bind.execute(text(
        "CREATE TYPE paymentstatus AS ENUM "
        "('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')"
    ))
    bind.execute(text(
        "ALTER TABLE payment ALTER COLUMN status TYPE paymentstatus "
        "USING status::text::paymentstatus"
    ))
    bind.execute(text("DROP TYPE paymentstatus_old"))
