"""add_city_id_country_id_to_company

Revision ID: 641926a360c3
Revises: 00270a7e8bc3
Create Date: 2026-03-28 23:55:10.732634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641926a360c3'
down_revision: Union[str, None] = '00270a7e8bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cities_id', table_name='city')
    op.create_index(op.f('ix_city_id'), 'city', ['id'], unique=False)
    op.add_column('company', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('country_id', sa.Integer(), nullable=True))
    op.drop_index('ix_companies_id', table_name='company')
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_foreign_key(None, 'company', 'country', ['country_id'], ['id'])
    op.create_foreign_key(None, 'company', 'city', ['city_id'], ['id'])
    op.drop_column('company', 'city')
    op.drop_index('ix_countries_id', table_name='country')
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.drop_index('ix_pools_id', table_name='pool')
    op.create_index(op.f('ix_pool_id'), 'pool', ['id'], unique=False)
    op.drop_index('ix_trainings_id', table_name='training')
    op.create_index(op.f('ix_training_id'), 'training', ['id'], unique=False)
    op.drop_constraint('trening_users_trening_id_fkey', 'training_users', type_='foreignkey')
    op.create_foreign_key(None, 'training_users', 'training', ['training_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_users', type_='foreignkey')
    op.create_foreign_key('trening_users_trening_id_fkey', 'training_users', 'training', ['training_id'], ['id'])
    op.drop_index(op.f('ix_training_id'), table_name='training')
    op.create_index('ix_trainings_id', 'training', ['id'], unique=False)
    op.drop_index(op.f('ix_pool_id'), table_name='pool')
    op.create_index('ix_pools_id', 'pool', ['id'], unique=False)
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.create_index('ix_countries_id', 'country', ['id'], unique=False)
    op.add_column('company', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.create_index('ix_companies_id', 'company', ['id'], unique=False)
    op.drop_column('company', 'country_id')
    op.drop_column('company', 'city_id')
    op.drop_index(op.f('ix_city_id'), table_name='city')
    op.create_index('ix_cities_id', 'city', ['id'], unique=False)
    # ### end Alembic commands ###
