"""drop contract months_count and installments_count

Revision ID: 71ae0c464615
Revises: cba4ec193751
Create Date: 2026-09-21 12:58:53.084782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ae0c464615'
down_revision: Union[str, None] = 'cba4ec193751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'months_count')
    op.drop_column('contract', 'installments_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('installments_count', sa.INTEGER(), autoincrement=False, nullable=False, server_default='1'))
    op.add_column('contract', sa.Column('months_count', sa.INTEGER(), autoincrement=False, nullable=False, server_default='1'))
    # ### end Alembic commands ###
    # Manual: server_default so the NOT NULL columns can be re-added to a
    # table that already has rows (autogenerate omits it).
