"""offering_price + contract: period_mode / installments_count

Revision ID: 776b52cb6b50
Revises: 14f3e224b1d4
Create Date: 2026-09-07 12:10:29.443421

A term's price is now the TOTAL for the whole term, split into
`installments_count` equal installments; `period_mode` decides whether the term
starts on the contract's own start_date (ROLLING) or snaps to the season grid
(FIXED_QUARTER). Both are added to offering_price and snapshotted onto contract.

Autogenerated, then adjusted: the enum type is created once up front (the two
add_columns would otherwise each try to CREATE TYPE), and the NOT NULL columns
carry a server_default while they backfill, which is dropped again so the model
stays the only place the default lives.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

# revision identifiers, used by Alembic.
revision: str = '776b52cb6b50'
down_revision: Union[str, None] = '14f3e224b1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _period_mode_type(dialect: str):
    """The already-created enum type — never auto-CREATE it per column."""
    if dialect == "postgresql":
        return PG_ENUM("FIXED_QUARTER", "ROLLING", name="periodmode", create_type=False)
    return sa.String(20)


def upgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        bind.execute(text("""
            DO $$ BEGIN
                CREATE TYPE periodmode AS ENUM ('FIXED_QUARTER','ROLLING');
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
        """))

    for table in ("offering_price", "contract"):
        op.add_column(table, sa.Column(
            "period_mode",
            _period_mode_type(dialect),
            nullable=False,
            server_default="ROLLING",
        ))
        op.add_column(table, sa.Column(
            "installments_count", sa.Integer(), nullable=False, server_default="1"
        ))
        # SQLite cannot ALTER a default; leaving it there is harmless.
        if dialect == "postgresql":
            op.alter_column(table, "period_mode", server_default=None)
            op.alter_column(table, "installments_count", server_default=None)


def downgrade() -> None:
    for table in ("contract", "offering_price"):
        op.drop_column(table, "installments_count")
        op.drop_column(table, "period_mode")

    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS periodmode")
