"""add_training_type_id_to_training

Revision ID: 8432ed24bdf9
Revises: 97efaf1e7398
Create Date: 2026-06-17 13:16:33.103025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8432ed24bdf9'
down_revision: Union[str, None] = '97efaf1e7398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('training_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training', 'training_type', ['training_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'training_type_id')
    # ### end Alembic commands ###
