"""replace offering_price and selection_offering with membership

Revision ID: 874bdb0952e7
Revises: 776b52cb6b50
Create Date: 2026-09-09 08:40:24.073299

Offers are no longer made per season or per selection, so the middle of the
season -> selection -> selection_offering -> offering_price chain has nothing
left to do. Pricing moves to `membership`: a flat per-company catalog whose
term length is a plain `months_count` (replacing the MONTHLY/QUARTERLY/YEARLY
BillingFrequency enum) and whose price is per month.

`season` and `selection` SURVIVE — training.season_id and tournament.season_id
are NOT NULL FKs, and selection is still the age-group catalog. Only their
`offerings` relationship is gone.

Contract is decoupled, not relinked: it keeps its own agreed amount and now
carries months_count instead of billing_frequency / period_mode / a pinned
offering_price_id. A membership_id FK is deliberately NOT added yet.

Autogenerated, then adjusted:
  * create_table("membership") was added by hand — autogenerate omitted it
    because create_tables() had already materialised the table in the dev DB.
  * the `program` enum type is created once up front rather than by the
    create_table, since offering_price may already own it.
  * contract.months_count carries a server_default while it backfills, dropped
    again so the model stays the only place the default lives.
  * unrelated exercise_option drift (a missing company_id column) that
    autogenerate swept in was removed — it predates this change.
  * billingfrequency / periodmode are dropped: nothing references them now.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

# revision identifiers, used by Alembic.
revision: str = '874bdb0952e7'
down_revision: Union[str, None] = '776b52cb6b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _program_type(dialect: str):
    """The already-created enum type — never auto-CREATE it per column."""
    if dialect == "postgresql":
        return PG_ENUM("SWIMMING", "WATERPOLO", name="program", create_type=False)
    return sa.String(20)


def upgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    # offering_price already owns this type; membership takes it over.
    if dialect == "postgresql":
        bind.execute(text("""
            DO $$ BEGIN
                CREATE TYPE program AS ENUM ('SWIMMING','WATERPOLO');
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
        """))

    # ── membership ──────────────────────────────────
    op.create_table(
        "membership",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("program", _program_type(dialect), nullable=False),
        sa.Column("months_count", sa.Integer(), nullable=False),
        sa.Column("price_month", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("installments_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "name", "program", name="uq_membership_company_name_program"
        ),
    )
    op.create_index("ix_membership_id", "membership", ["id"], unique=False)
    op.create_index("ix_membership_company_id", "membership", ["company_id"], unique=False)

    # ── contract: months_count replaces the term enums ──
    op.add_column(
        "contract",
        sa.Column("months_count", sa.Integer(), nullable=False, server_default="1"),
    )
    # SQLite cannot ALTER a default; leaving it there is harmless.
    if dialect == "postgresql":
        op.alter_column("contract", "months_count", server_default=None)

    op.drop_index("ix_contract_offering_price_id", table_name="contract")
    op.drop_constraint("contract_offering_price_id_fkey", "contract", type_="foreignkey")
    op.drop_column("contract", "offering_price_id")
    op.drop_column("contract", "period_mode")
    op.drop_column("contract", "billing_frequency")

    # ── drop the old chain (offering_price first — it FKs the offering) ──
    op.drop_index("ix_offering_price_offering_id", table_name="offering_price")
    op.drop_index("ix_offering_price_id", table_name="offering_price")
    op.drop_table("offering_price")

    op.drop_index("ix_selection_offering_selection_id", table_name="selection_offering")
    op.drop_index("ix_selection_offering_season_id", table_name="selection_offering")
    op.drop_index("ix_selection_offering_id", table_name="selection_offering")
    op.drop_table("selection_offering")

    # Nothing references these any more.
    if dialect == "postgresql":
        op.execute("DROP TYPE IF EXISTS billingfrequency")
        op.execute("DROP TYPE IF EXISTS periodmode")


def downgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        bind.execute(text("""
            DO $$ BEGIN
                CREATE TYPE billingfrequency AS ENUM ('MONTHLY','QUARTERLY','YEARLY');
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
            DO $$ BEGIN
                CREATE TYPE periodmode AS ENUM ('FIXED_QUARTER','ROLLING');
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
        """))

    def _enum(name, *values):
        if dialect == "postgresql":
            return PG_ENUM(*values, name=name, create_type=False)
        return sa.String(20)

    op.create_table(
        "selection_offering",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["season_id"], ["season.id"]),
        sa.ForeignKeyConstraint(["selection_id"], ["selection.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("selection_id", "season_id", name="uq_offering_selection_season"),
    )
    op.create_index("ix_selection_offering_id", "selection_offering", ["id"], unique=False)
    op.create_index("ix_selection_offering_season_id", "selection_offering", ["season_id"], unique=False)
    op.create_index("ix_selection_offering_selection_id", "selection_offering", ["selection_id"], unique=False)

    op.create_table(
        "offering_price",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("offering_id", sa.Integer(), nullable=False),
        sa.Column("program", _program_type(dialect), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("billing_frequency", _enum("billingfrequency", "MONTHLY", "QUARTERLY", "YEARLY"), nullable=False),
        sa.Column("period_mode", _enum("periodmode", "FIXED_QUARTER", "ROLLING"), nullable=False, server_default="ROLLING"),
        sa.Column("installments_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["offering_id"], ["selection_offering.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("offering_id", "program", name="uq_offering_price_program"),
    )
    op.create_index("ix_offering_price_id", "offering_price", ["id"], unique=False)
    op.create_index("ix_offering_price_offering_id", "offering_price", ["offering_id"], unique=False)

    op.add_column("contract", sa.Column(
        "billing_frequency",
        _enum("billingfrequency", "MONTHLY", "QUARTERLY", "YEARLY"),
        nullable=False, server_default="MONTHLY",
    ))
    op.add_column("contract", sa.Column(
        "period_mode",
        _enum("periodmode", "FIXED_QUARTER", "ROLLING"),
        nullable=False, server_default="ROLLING",
    ))
    op.add_column("contract", sa.Column("offering_price_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "contract_offering_price_id_fkey", "contract", "offering_price",
        ["offering_price_id"], ["id"],
    )
    op.create_index("ix_contract_offering_price_id", "contract", ["offering_price_id"], unique=False)
    if dialect == "postgresql":
        op.alter_column("contract", "billing_frequency", server_default=None)
        op.alter_column("contract", "period_mode", server_default=None)
    op.drop_column("contract", "months_count")

    op.drop_index("ix_membership_company_id", table_name="membership")
    op.drop_index("ix_membership_id", table_name="membership")
    op.drop_table("membership")
