"""add_company_type_to_company

Revision ID: 8d9961a665ab
Revises: 641926a360c3
Create Date: 2026-04-03 13:31:24.137362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9961a665ab'
down_revision: Union[str, None] = '641926a360c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_type', sa.String(length=20), server_default='CLUB', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'company_type')
    # ### end Alembic commands ###
