"""add training_type and swimming_discipline tables with company_id

Revision ID: 8eec4a7e3565
Revises: e7ffee1c4922
Create Date: 2026-06-16 17:31:00.316068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eec4a7e3565'
down_revision: Union[str, None] = 'e7ffee1c4922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swimming_discipline', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'swimming_discipline', 'company', ['company_id'], ['id'])
    op.add_column('training_type', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'training_type', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_type', type_='foreignkey')
    op.drop_column('training_type', 'company_id')
    op.drop_constraint(None, 'swimming_discipline', type_='foreignkey')
    op.drop_column('swimming_discipline', 'company_id')
    # ### end Alembic commands ###
