"""add contract.membership_id

Revision ID: 9107213df15f
Revises: 8bf1e1067ad8
Create Date: 2026-09-09 13:02:44.287320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9107213df15f'
down_revision: Union[str, None] = '8bf1e1067ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('membership_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contract_membership_id'), 'contract', ['membership_id'], unique=False)
    op.create_foreign_key('fk_contract_membership_id', 'contract', 'membership', ['membership_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_contract_membership_id', 'contract', type_='foreignkey')
    op.drop_index(op.f('ix_contract_membership_id'), table_name='contract')
    op.drop_column('contract', 'membership_id')
    # ### end Alembic commands ###
