"""remove_payed_users_from_training_add_training_users_list

Revision ID: 97efaf1e7398
Revises: 8eec4a7e3565
Create Date: 2026-06-17 12:00:38.460430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97efaf1e7398'
down_revision: Union[str, None] = '8eec4a7e3565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_users')
    op.drop_column('training', 'payed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('payed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('training_users',
    sa.Column('training_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], name='training_users_training_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='trening_users_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('training_id', 'user_id', name='trening_users_pkey')
    )
    # ### end Alembic commands ###
