"""add training segments; drop training.training_type_id

Revision ID: 986eddaf2249
Revises: 6da11a17513f
Create Date: 2026-07-11 17:24:19.073362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986eddaf2249'
down_revision: Union[str, None] = '6da11a17513f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_type', sa.Enum('SWIMMING', 'SPARRING', 'GYM', 'WORK_WITH_BALL', name='segmenttype'), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_type', 'code')
    )
    op.create_index(op.f('ix_exercise_option_id'), 'exercise_option', ['id'], unique=False)
    op.create_table('training_segment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.Enum('SWIMMING', 'SPARRING', 'GYM', 'WORK_WITH_BALL', name='segmenttype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_segment_id'), 'training_segment', ['id'], unique=False)
    op.create_index(op.f('ix_training_segment_training_id'), 'training_segment', ['training_id'], unique=False)
    op.create_table('segment_exercise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('exercise_option_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('meters', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_option_id'], ['exercise_option.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['training_segment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_exercise_id'), 'segment_exercise', ['id'], unique=False)
    op.create_index(op.f('ix_segment_exercise_segment_id'), 'segment_exercise', ['segment_id'], unique=False)
    op.create_table('segment_sparring',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('opponent_company_id', sa.Integer(), nullable=False),
    sa.Column('our_score', sa.Integer(), nullable=True),
    sa.Column('opponent_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opponent_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['training_segment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id')
    )
    op.create_index(op.f('ix_segment_sparring_id'), 'segment_sparring', ['id'], unique=False)
    op.create_table('sparring_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_sparring_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('GOAL', 'ASSIST', 'SAVE', 'EXCLUSION', 'PENALTY', name='eventtype'), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_sparring_id'], ['segment_sparring.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sparring_event_id'), 'sparring_event', ['id'], unique=False)
    op.create_index(op.f('ix_sparring_event_segment_sparring_id'), 'sparring_event', ['segment_sparring_id'], unique=False)

    # ── Data migration ────────────────────────────────────────────
    # Turn each training's old training_type into one segment at position 1.
    # The old type had no SegmentType meaning, so default to SWIMMING and keep
    # the old type name in the segment's notes for reference.
    op.execute(
        """
        INSERT INTO training_segment (training_id, segment_type, position, notes)
        SELECT t.id, 'SWIMMING'::segmenttype, 1, tt.name
        FROM training t
        LEFT JOIN training_type tt ON tt.id = t.training_type_id
        """
    )

    op.drop_constraint('training_training_type_id_fkey', 'training', type_='foreignkey')
    op.drop_column('training', 'training_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The original training_type_id can't be recovered — segments replaced it.
    # Re-add the column nullable, best-effort backfill any training_type, then
    # enforce NOT NULL so the schema matches the pre-migration shape.
    op.add_column('training', sa.Column('training_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute(
        """
        UPDATE training
        SET training_type_id = (SELECT id FROM training_type ORDER BY id LIMIT 1)
        WHERE training_type_id IS NULL
        """
    )
    op.alter_column('training', 'training_type_id', nullable=False)
    op.create_foreign_key('training_training_type_id_fkey', 'training', 'training_type', ['training_type_id'], ['id'])
    op.drop_index(op.f('ix_sparring_event_segment_sparring_id'), table_name='sparring_event')
    op.drop_index(op.f('ix_sparring_event_id'), table_name='sparring_event')
    op.drop_table('sparring_event')
    op.drop_index(op.f('ix_segment_sparring_id'), table_name='segment_sparring')
    op.drop_table('segment_sparring')
    op.drop_index(op.f('ix_segment_exercise_segment_id'), table_name='segment_exercise')
    op.drop_index(op.f('ix_segment_exercise_id'), table_name='segment_exercise')
    op.drop_table('segment_exercise')
    op.drop_index(op.f('ix_training_segment_training_id'), table_name='training_segment')
    op.drop_index(op.f('ix_training_segment_id'), table_name='training_segment')
    op.drop_table('training_segment')
    op.drop_index(op.f('ix_exercise_option_id'), table_name='exercise_option')
    op.drop_table('exercise_option')
    # ### end Alembic commands ###
