"""add group_index to segment_exercise

Revision ID: 9fc692c4bdcf
Revises: 2140c095f678
Create Date: 2026-07-12 12:44:40.368456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc692c4bdcf'
down_revision: Union[str, None] = '2140c095f678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment_exercise', sa.Column('group_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment_exercise', 'group_index')
    # ### end Alembic commands ###
