"""sparring home/away company, drop scores

Revision ID: a5721e408757
Revises: 4e7cf07610c9
Create Date: 2026-07-19 18:30:28.818060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5721e408757'
down_revision: Union[str, None] = '4e7cf07610c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment_sparring', sa.Column('home_company_id', sa.Integer(), nullable=True))
    op.add_column('segment_sparring', sa.Column('away_company_id', sa.Integer(), nullable=True))
    op.drop_constraint('segment_sparring_opponent_company_id_fkey', 'segment_sparring', type_='foreignkey')
    op.create_foreign_key(None, 'segment_sparring', 'company', ['away_company_id'], ['id'])
    op.create_foreign_key(None, 'segment_sparring', 'company', ['home_company_id'], ['id'])
    op.drop_column('segment_sparring', 'opponent_company_id')
    op.drop_column('segment_sparring', 'opponent_score')
    op.drop_column('segment_sparring', 'our_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment_sparring', sa.Column('our_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('segment_sparring', sa.Column('opponent_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('segment_sparring', sa.Column('opponent_company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'segment_sparring', type_='foreignkey')
    op.drop_constraint(None, 'segment_sparring', type_='foreignkey')
    op.create_foreign_key('segment_sparring_opponent_company_id_fkey', 'segment_sparring', 'company', ['opponent_company_id'], ['id'])
    op.drop_column('segment_sparring', 'away_company_id')
    op.drop_column('segment_sparring', 'home_company_id')
    # ### end Alembic commands ###
