"""add_is_active_to_company

Revision ID: aa593ad8fbcc
Revises: c3d0b567d15e
Create Date: 2026-04-29 18:08:48.645459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa593ad8fbcc'
down_revision: Union[str, None] = 'c3d0b567d15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'is_active')
    # ### end Alembic commands ###
