"""add_address_number_phone_email_to_pools

Revision ID: bb12a96aca43
Revises: ab9e823d892e
Create Date: 2026-03-27 14:19:13.839999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb12a96aca43'
down_revision: Union[str, None] = 'ab9e823d892e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pools', sa.Column('address_number', sa.String(length=50), nullable=True))
    op.add_column('pools', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('pools', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column('pools', 'lanes')
    op.alter_column('trainings', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_index('ix_trenings_id', table_name='trainings')
    op.create_index(op.f('ix_trainings_id'), 'trainings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainings_id'), table_name='trainings')
    op.create_index('ix_trenings_id', 'trainings', ['id'], unique=False)
    op.alter_column('trainings', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.add_column('pools', sa.Column('lanes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pools', 'email')
    op.drop_column('pools', 'phone')
    op.drop_column('pools', 'address_number')
    # ### end Alembic commands ###
