"""add_pool_id_to_training

Revision ID: c3d0b567d15e
Revises: 6965b30123fb
Create Date: 2026-04-03 16:59:27.236535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d0b567d15e'
down_revision: Union[str, None] = '6965b30123fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('pool_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training', 'company', ['pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'pool_id')
    # ### end Alembic commands ###
