"""add season_selection_user

Revision ID: cba4ec193751
Revises: d2c14bc3e4d2
Create Date: 2026-09-21 11:19:31.043058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba4ec193751'
down_revision: Union[str, None] = 'd2c14bc3e4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate against the dev DB came out empty: init_db()'s create_all
    # had already built the table there. The ops below are Alembic's own
    # autogenerate output against a DB without the table, so every other
    # environment still gets it.
    op.create_table('season_selection_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selection_id'], ['selection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'selection_id', 'user_id', name='uq_season_selection_user')
    )
    op.create_index(op.f('ix_season_selection_user_id'), 'season_selection_user', ['id'], unique=False)
    op.create_index(op.f('ix_season_selection_user_season_id'), 'season_selection_user', ['season_id'], unique=False)
    op.create_index(op.f('ix_season_selection_user_selection_id'), 'season_selection_user', ['selection_id'], unique=False)
    op.create_index(op.f('ix_season_selection_user_user_id'), 'season_selection_user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_selection_user_user_id'), table_name='season_selection_user')
    op.drop_index(op.f('ix_season_selection_user_selection_id'), table_name='season_selection_user')
    op.drop_index(op.f('ix_season_selection_user_season_id'), table_name='season_selection_user')
    op.drop_index(op.f('ix_season_selection_user_id'), table_name='season_selection_user')
    op.drop_table('season_selection_user')
    # ### end Alembic commands ###
