"""add ACADEMY company type and company.academy_id

Revision ID: d2c14bc3e4d2
Revises: e20d836e0be0
Create Date: 2026-09-18 13:39:11.617312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c14bc3e4d2'
down_revision: Union[str, None] = 'e20d836e0be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('academy_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_company_academy_id'), 'company', ['academy_id'], unique=False)
    op.create_foreign_key(
        'fk_company_academy_id_company', 'company', 'company', ['academy_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_company_academy_id_company', 'company', type_='foreignkey')
    op.drop_index(op.f('ix_company_academy_id'), table_name='company')
    op.drop_column('company', 'academy_id')
    # ### end Alembic commands ###
