"""add_countries_cities_tables_and_update_pools

Revision ID: f711e4cfdd38
Revises: bb12a96aca43
Create Date: 2026-03-28 23:31:00.112236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f711e4cfdd38'
down_revision: Union[str, None] = 'bb12a96aca43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pools', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('pools', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('pools', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_foreign_key(None, 'pools', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(None, 'pools', 'cities', ['city_id'], ['id'])
    op.drop_column('pools', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pools', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pools', type_='foreignkey')
    op.drop_constraint(None, 'pools', type_='foreignkey')
    op.drop_column('pools', 'is_active')
    op.drop_column('pools', 'country_id')
    op.drop_column('pools', 'city_id')
    # ### end Alembic commands ###
