"""make_pool_id_and_training_type_id_not_null

Revision ID: fcce885d1aa0
Revises: 8432ed24bdf9
Create Date: 2026-06-19 13:49:55.838220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcce885d1aa0'
down_revision: Union[str, None] = '8432ed24bdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("UPDATE training SET pool_id = 1 WHERE pool_id IS NULL")
    op.execute("UPDATE training SET training_type_id = 1 WHERE training_type_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training', 'pool_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training', 'training_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training', 'training_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('training', 'pool_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
